### ISSUE TITLE
cross-platform support + no-color-fallback

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-pretty-assertions#1]
Not all terminals support ANSI escape characters (e.g. on windows).

It would be nice, if
(a) this would also work on windows
(b) color codes are surpressed when the current terminal does not support them

I would like to switch to the format of `git diff --word-diff`, which is also readable without colors
```diff
The quick [-red-]{+brown+} fox jumps over the lazy dog
```

This should be solved in the underlying `difference` crate, see https://github.com/johannhof/difference.rs/issues/15.

Note: The discussion below got a little side-tracked... ^^

**Comment by fflorent** [comment]
FWIW, for PR #9, I checked how the output renders on Windows 10 (using cargo test). 

It works pretty well (using a classic cmd window)

![image](https://user-images.githubusercontent.com/371705/27515389-5bd22ee6-59a2-11e7-9c28-b73d6575cee1.png)

**Comment by colin-kiegel** [comment]
great, thanks for the info.

**Comment by fflorent** [comment]
Erf, bad news: https://superuser.com/a/1105718/134164

That's a new feature in Windows 10. Probably not supported in Windows 8 and 7, except if the user use compatible terminals.

**Comment by turboladen** [comment]
I dunno if this is the same issue or not but I'm on OSX (iTerm2) and the fancy arrows don't render for me (either?). I tried with a number of different fonts, to no avail; here's output from v0.3.2:

<img width="248" alt="screen shot 2017-08-31 at 2 07 43 pm" src="https://user-images.githubusercontent.com/142010/29945403-d9960f0e-8e55-11e7-8ded-2bbcf61e8ab2.png">

**Comment by colin-kiegel** [comment]
ok, thanks for the info. Could you check which of these render in your terminal?

```bash
$ echo "+ ⭬ ⭢ ⭲ ⮞ ⏵ ⯈ ▶"
```

**Comment by fflorent** [comment]
@colin-kiegel same issue here.

> $ echo "+ ⭬ ⭢ ⭲ ⮞ ⏵ ⯈ ▶"

the first and the last one are the only ones to be well displayed on my terminal.

Florent

**Comment by turboladen** [comment]
Here's what I get:

<img width="602" alt="screen shot 2017-08-31 at 2 16 57 pm" src="https://user-images.githubusercontent.com/142010/29945694-1c27ffc0-8e57-11e7-8ed1-698ec2627c0f.png">

> PS: Is iTerm2 the standard terminal?

No, it's not, but I'd wager it's quite common for developers on OSX to use. Looks like the default Terminal app on OSX renders the same though:

<img width="424" alt="screen shot 2017-08-31 at 2 18 29 pm" src="https://user-images.githubusercontent.com/142010/29945750-58e69138-8e57-11e7-8fbe-4bd99ecce22e.png">

**Comment by colin-kiegel** [comment]
ah, ok. Good to know. 

It's probably safest if we stick to something like https://en.wikipedia.org/wiki/Windows_Glyph_List_4 or even `<` / `>`. We could still make those bold to make it more visible.

Just to know our alternatives better - could someone of you check again, which of these work?
```bash
$ echo "→➤⮞❱❯❭"
```

**Comment by turboladen** [comment]
Most of those work for me:

<img width="187" alt="screen shot 2017-08-31 at 2 29 13 pm" src="https://user-images.githubusercontent.com/142010/29946104-df63b21c-8e58-11e7-84bf-c5c339f6656c.png">

**Comment by fflorent** [comment]
Same here:
![image](https://user-images.githubusercontent.com/371705/29946537-0d6b4d94-8ea6-11e7-8fb0-0f4fc10c2081.png)

**Comment by colin-kiegel** [comment]
Ok, I'm [asking a broader audience](https://users.rust-lang.org/t/mega-assert-eq-with-colorful-diff-drop-in-replacement/10101/21) to double check the glyphs that worked for both of you
```+ > → ❭ ❯ ❱ ▶ ➤```

**Comment by turboladen** [comment]
Sweet! Thanks for being so responsive!

**Comment by colin-kiegel** [comment]
I switched to `◀` / `▶` glyphs - fingers crossed. ;-)

**Comment by Marwes** [comment]
`+ > → ❭ ❯ ❱ ▶ ➤` does not work well for me :/.
![capture](https://user-images.githubusercontent.com/957312/29988212-618b7928-8f6c-11e7-8489-50bfe948614b.PNG)


Windows 10 with Git Bash.

**Comment by turboladen** [comment]
### iTerm2 

Font: 12pt [Fira Mono](https://github.com/tonsky/FiraCode) font

It renders for me, although if I'm picky, with my typical settings the spacing is kinda funky:

![screen shot 2017-09-01 at 2 23 54 pm](https://user-images.githubusercontent.com/142010/29988271-43e1b3ec-8f21-11e7-955f-edeb2699540f.png)

----

### Terminal

Font: Menlo 11pt (default, IIRC)

Looks better here although still slightly a little smushed... 

![screen shot 2017-09-01 at 2 28 35 pm](https://user-images.githubusercontent.com/142010/29988402-fc1ac944-8f21-11e7-9dd4-e86bfb9f6d7b.png)

----

For my part, it'd be nice if spacing was better, but if it was like this in the first place I probably wouldn't have bothered commenting.

**Comment by colin-kiegel** [comment]
@turboladen ok, it's plain `<` and `>` now. :-)

**Comment by turboladen** [comment]
Works for me! Thanks!

**Comment by Michael-F-Bryan** [comment]
At work I have to work on a windows machine and every now and then I notice that the colouring breaks my terminal. It looks almost like at the end of a coloured section it'll forget to revert back to the default colour, meaning from then onwards my terminal's text will be green or red.

I'd probably be better off reporting that to the colour library you use under the hood, just thought I'd let you know that colour support for non-unix can be a bit dodgy sometimes.

**Comment by colin-kiegel** [comment]
@Michael-F-Bryan: Thx. Can you still reproduce this? If so, please report a minimal example - ideally as an independent ticket, mentioning this one. :-)

**Comment by Screwtapello** [comment]
There's another situation where ANSI colours generally aren't available: when the compiler output is piped into an editor or IDE. Much like the Rust compiler's warnings are still useful when colour is disabled, it would be nice if this crate's output was just as useful without colour output.

Are you familiar with how Python's unit test framework formats failed assertions?

```
  Some(
      Foo {
-         lorem: "Hello World!",
?                         -
+         lorem: "Hello Wrold!",
?                        +
          ipsum: 42,
          dolor: Ok(
-             "hey"
+             "hey ho!"
?                 ++++
          )
      }
  )
```

Being familiar with classic `diff -u` output, I immediately recognised the leading `-` and `+` characters on the lines that differed, and once I'd figured that out, it was pretty obvious what the `?` lines were pointing out. Colour would be an improvement, but it's still perfectly legible without.

**Comment by colin-kiegel** [comment]
closing in favour of a new ticket #31
