### ISSUE TITLE
assert_eq! too strict re strings

### ISSUE THREAD

**Issue by kw217** [colin-kiegel/rust-pretty-assertions#10]
The following test passes using the standard `assert_eq!`, but fails to compile using `pretty_assertions`:
```rust
    #[test]
    fn it_works() {
	let s0: &'static str = "foo";
	let s1: String = "foo".to_string();
	assert_eq!(s0, s1);
    }
```

The error is
```
error[E0308]: mismatched types
  --> src/lib.rs:10:2
   |
10 | 	assert_eq!(s0, s1);
   | 	^^^^^^^^^^^^^^^^^^^ expected &str, found struct `std::string::String`
   |
   = note: expected type `&&str`
              found type `&std::string::String`
   = note: this error originates in a macro outside of the current crate

```

Please can the behaviour of `assert_eq!` be relaxed, so `pretty_assertions` can truly be a drop-in replacement? Thanks.

**Comment by fflorent** [comment]
Hi!

Disclaimer: I am not the maintainer of the crate.

I opened PR #11 for this. Feedback is welcome (even for bikeshedding, I would like to learn best practices in Rust). Thanks :).

Florent

**Comment by colin-kiegel** [comment]
fixed in v0.2.1 :-)

**Comment by fflorent** [comment]
Great!

**Comment by kw217** [comment]
Brilliant, thanks @colin-kiegel !

**Comment by colin-kiegel** [comment]
I forward all kudos to @fflorent who fixed this ;-)
