### ISSUE TITLE
why are old versions of pretty-assertion more popular?

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/rust-pretty-assertions#14]
Why do people prefer old versions? :confused:
How can we improve this?

# Downloads as of 2017-10-17

## [... over the last 90 days](https://crates.io/crates/pretty-assertions#crate-downloads)

![crate downloads](https://user-images.githubusercontent.com/7691186/31678174-92e588cc-b36d-11e7-8d4f-75182fe90096.png)

## ... per version

| Version                                          | Downloads | Release Date      |
|--------------------------------------------------|-----------|-------------------|
| [0.1.0](https://crates.io/crates/pretty-assertions/0.1.0) | 105       | March 26, 2017    |
| [0.1.1](https://crates.io/crates/pretty-assertions/0.1.1) | 44        | March 29, 2017    |
| **[0.1.2](https://crates.io/crates/pretty-assertions/0.1.2)** | **16_725**    | **March 29, 2017**    |
| [0.2.0](https://crates.io/crates/pretty-assertions/0.2.0) | 708       | April 29, 2017    |
| **[0.2.1](https://crates.io/crates/pretty-assertions/0.2.1)** | **6_295**     | **June 24, 2017**     |
| [0.3.0](https://crates.io/crates/pretty-assertions/0.3.0) | 26        | August 30, 2017   |
| [0.3.1](https://crates.io/crates/pretty-assertions/0.3.1) | 18        | August 31, 2017   |
| [0.3.2](https://crates.io/crates/pretty-assertions/0.3.2) | 20        | August 31, 2017   |
| [0.3.3](https://crates.io/crates/pretty-assertions/0.3.3) | 18        | September 1, 2017 |
| **[0.3.4](https://crates.io/crates/pretty-assertions/0.3.4)** | **573**       | **September 2, 2017** |
| [0.4.0](https://crates.io/crates/pretty-assertions/0.4.0) | 8         | October 15, 2017  |

# `v0.1.2`
![v0.1.2](https://raw.githubusercontent.com/colin-kiegel/rust-pretty-assertions/v0.1.2/examples/pretty_assertion.png)

# `v0.2.1`
![v0.2.1](https://raw.githubusercontent.com/colin-kiegel/rust-pretty-assertions/v0.2.1/examples/pretty_assertion.png)

# `v0.3.4`
![v0.3.4](https://raw.githubusercontent.com/colin-kiegel/rust-pretty-assertions/v0.3.4/examples/pretty_assertion.png)

# `v0.4.0`
![v0.4.0](https://raw.githubusercontent.com/colin-kiegel/rust-pretty-assertions/v0.4.0/examples/pretty_assertion.png)

**Comment by fflorent** [comment]
Oh ! Good question. Is there a room for this question on some topics in https://users.rust-lang.org/ ?

Florent

**Comment by colin-kiegel** [comment]
There are 61 [`Cargo.toml` files on github containing the string `pretty_assertions`](https://github.com/search?l=TOML&q=pretty_assertions+&type=Code&utf8=%E2%9C%93)  (as of 2017-10-18). I checked roughly 20 of them via blame. I compared the crate version in `Cargo.toml` with the most recent `pretty_assertions` version at the commit date the dependency was introduced.

Only 1 out of 20 crates (5%) was using an outdated version. Thats not a significant number.
Which means 95% were using the most recent version at the time of introducing `pretty_assertions`.

So, at first glance it looks like (a) earlier versions of `pretty_assertions` just had more impact on the crates and (b) a lot of people are not _updating_ their dependencies very regularly. Could that be it?

- `v0.1.2` had 16_725 downloads in 152 days (110 per day)
- `v0.2.1` had 6_295 downloads in 116 days (54 per day)
- `v0.3.4` had 573 downloads in 46 days (12 per day)

**Comment by fflorent** [comment]
A question comes to my mind: how relevant are those metrics (i.e. the number of downloads) for the popularity?

Consider this scenario: if a company use a crate in a CI and that CI is run hundreds of time a day (without any cache), can that distort the metrics?

Probably worth to know more about how those metrics work, maybe by discussing with the maintainers of crates.io.

**Comment by colin-kiegel** [comment]
yes, it's not a measure of "unique projects" and can be heavily distorted by single very CI-active projects. I think most important part is to ask people if there is something wrong with newer versions. :-) Like on the rust-lang post (or here).

**Comment by Enet4** [comment]
I can speak from personal experience that I installed `pretty_assertions` during the pre-release development of my crate `nifti`, and it was quite useful then. Once that step was done, and the bugs were squashed, there was little incentive to keep it updated as a dev dependency.

I can also understand some reluctance from the fact that the crate is still on a 0 major version, which might give the wrong impression that a minor version bump requires adjustments to user code. When do you think it's appropriate to release v1.0?

**Comment by colin-kiegel** [comment]
@Enet4 thx for your feedback.

1.0 is a good question. A _must-have_ is a good cross-platform story #1 and some bugs fixed in our dependency `difference.rs` (https://github.com/johannhof/difference.rs/issues/25). Apart from that I would just ask people what they expect from 1.0.
