### ISSUE TITLE
Expected strings are hard to maintain and to review

### ISSUE THREAD

**Issue by fflorent** [colin-kiegel/rust-pretty-assertions#18]
The readability of the expected strings in the tests of the crate tends to be a bit tedious to maintain and to read like here:
https://github.com/colin-kiegel/rust-pretty-assertions/blob/master/tests/assert_eq.rs#L78-L93

I wonder if there is no nicer way to write them.

Florent

**Comment by colin-kiegel** [comment]
Indeed! :-)

I usually pipe all `cargo test` output to a file and copy-paste from there.. If the output changes for a lot of tests, this is (a) a painfully slow process.. and (b) it's far from readable.. But I don't have a better idea.

**Comment by colin-kiegel** [comment]
I don't expect a lightweight solution for this ...
