### ISSUE TITLE
Rust 2018 documentation

### ISSUE THREAD

**Issue by asomers** [colin-kiegel/rust-pretty-assertions#25]
In the 2018 edition, `#[macro_use]` is gone, or at least deprecated.  Instead, the new way to import macros is just like importing functions.  So using pretty_assertions in Rust 2018 requires a `use pretty_assertions::{assert_eq, assert_ne};`.  The docs should mention that.

Unfortunately, that `use` statement must be repeated in *every test module*.  It would be great if you could find a better way for Rust 2018.

https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html

**Comment by colin-kiegel** [comment]
Thx. I updated the docs in master - the next release `0.6.0` will target the Rust 2018 edition
