### ISSUE TITLE
clarify "22 lines of code" in README

### ISSUE THREAD

**Issue by torkleyy** [colin-kiegel/rust-pretty-assertions#4]
> All that pretty_assertions does is to replace the assert_eq! macro with just about 22 lines of code.

This sounds like every invocation would insert 22 lines into the calling function.

**Comment by colin-kiegel** [comment]
@torkleyy Thanks for the report and reminding me to get rid of that sentence. :-)

The clarification is this: At the time of writing that sentence, the code of the crate was [exactly 22 lines](https://github.com/colin-kiegel/rust-pretty-assertions/blob/162f407eb8f627185ce70c0475a661b7480f0038/src/lib.rs#L54-L75). My original intention was to say that this crate is really simple - but I now believe this information is not very useful and I don't want to update that number... The next commit will remove that whole bullet point.

If anyone is worried about the performance of `assert_eq!`, then yes, calculating the diff _will_ be somewhat slower. But it's only calculated if the values are different.
