### ISSUE TITLE
Consider pretty-print

### ISSUE THREAD

**Issue by antoyo** [colin-kiegel/rust-pretty-assertions#5]
Hello.
It would be nice to have an option that would make this crate use `{:#?}` instead of `{:?}` to pretty-print the values.
Thanks to add this.

**Comment by colin-kiegel** [comment]
Thx for the suggestion. I'm inclined to accept a PR with this behind a feature flag if it's also well documented. :-)

**Comment by fflorent** [comment]
I am working on the issue currently. The PR will probably come soon :).

Florent

**Comment by colin-kiegel** [comment]
released with v0.3.0. :-)
