### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by nbigaouette-eai** [colin-kiegel/rust-pretty-assertions#6]
The README.md suggests adding the crate in `[dev-dependency]` so that it only gets included in tests build.

This is a typo: the proper TOML section should be `[dev-dependencies]` (plural).

See the [cargo documentation](http://doc.crates.io/specifying-dependencies.html#development-dependencies).

**Comment by colin-kiegel** [comment]
Right. Since I'm on holiday, I'd appreciate a PR for this typo in readme and the lib.rs doc. :-)
