### ISSUE TITLE
LICENSE files missing from published crates since version 1.0.0

### ISSUE THREAD

**Issue by decathorpe** [colin-kiegel/rust-pretty-assertions#86]
Looks like the published crate was moved from the repository root to a workspace subdirectory in this commit: https://github.com/colin-kiegel/rust-pretty-assertions/commit/0df5d7a50fbb0d4c71ebeb20e528ae104ecd01ca

This results in LICENSE files no longer being included in published crates. Since both MIT and Apache-2.0 licenses require the license text to be included in redistributed sources, please re-include those files in published pretty_assertions crates (adding symlinks `LICENSE-{APACHE,MIT} -> ../LICENSE-{APACHE,MIT}` should do the trick, assuming you don't run `cargo publish` from a windows machine that does not support symlinks).

Thanks!

**Comment by tommilligan** [comment]
Thanks for reporting this - fixed in #87. This will be included in the next release when there is one
